name: Jonas
version: '1.0'
main: geburtstag.jonas.Jonas
api-version: 1.18
authors: [Jonas, Liam]
description: Minecraft Plugin für Jonas Geburtstag
website: https://kauper.de

commands:
  heal:
    description: Dieser Befehl heilt dich.
    aliases: ["h"]
  home:
    description: Teleport zurück nach hause.
    aliases: [ "spawn" ]

permissions:
  geburtstag.Jonas.heal:
    description: Dieser Befehl heilt dich.
    default: op
  geburtstag.Jonas.home:
    description: Teleport zurück nach hause.
    default: op